apiVersion: v1
kind: Service
metadata:
  name: ourchat-service
spec:
  selector:
    app: ourchat
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
  nodePort: 30080  # Specify the NodePort (replace with your desired port)
